// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLVatTuPhongThiNghiem.Data;

#nullable disable

namespace Cuba_Staterkit.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.Entities.DanhGiaCapDo", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int>("CapDo")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaTTB")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDanhGia")
                        .HasColumnType("int");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaTTB");

                    b.HasIndex("NguoiDanhGia");

                    b.ToTable("DanhGiaCapDo", (string)null);
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.Entities.LichSuSuaChua", b =>
                {
                    b.Property<int>("MaSuaChua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSuaChua"));

                    b.Property<decimal?>("ChiPhi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiSuaChua")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaTTB")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiThucHien")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaSuaChua");

                    b.HasIndex("MaTTB");

                    b.HasIndex("NguoiThucHien");

                    b.ToTable("LichSuSuaChua", (string)null);
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.Entities.LichThucHanh", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLich"));

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKT")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLich");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("LichThucHanh", (string)null);
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.Entities.Loai", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoai");

                    b.ToTable("Loai", (string)null);
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.Entities.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.Entities.PhongMay", b =>
                {
                    b.Property<int>("MaPhongMay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhongMay"));

                    b.Property<string>("TenPhongMay")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhongMay");

                    b.ToTable("PhongMay", (string)null);
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.Entities.ThuongHieu", b =>
                {
                    b.Property<int>("MaThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuongHieu"));

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaThuongHieu");

                    b.ToTable("ThuongHieu", (string)null);
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.Entities.TrangTB", b =>
                {
                    b.Property<int>("MaTTB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTTB"));

                    b.Property<int?>("GiaTien")
                        .HasColumnType("int");

                    b.Property<int?>("MaLich")
                        .HasColumnType("int");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhongMay")
                        .HasColumnType("int");

                    b.Property<int?>("MaThuongHieu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoLanSua")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTTB");

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaPhongMay");

                    b.HasIndex("MaThuongHieu");

                    b.ToTable("TrangTB", (string)null);
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.Entities.XuatNhapTon", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieu"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiPhieu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MaTTB")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaTTB");

                    b.HasIndex("NguoiTao");

                    b.ToTable("XuatNhapTon", (string)null);
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.ViewModels.DanhGiaCapDoViewModel", b =>
                {
                    b.Property<int>("CapDo")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaDanhGia")
                        .HasColumnType("int");

                    b.Property<int>("MaTTB")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("TenNguoiDanhGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("DanhGiaCapDoViewModel");
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.ViewModels.LichThucHanhViewModel", b =>
                {
                    b.Property<int>("MaLich")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianBD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKT")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("LichThucHanhViewModel");
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.ViewModels.SuaChuaViewModel", b =>
                {
                    b.Property<decimal?>("ChiPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiSuaChua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaSuaChua")
                        .HasColumnType("int");

                    b.Property<int>("MaTTB")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiThucHien")
                        .HasColumnType("int");

                    b.Property<string>("TenNguoiThucHien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrangMoi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SuaChuaViewModel");
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.ViewModels.ThongKeSuDungTheoThangViewModel", b =>
                {
                    b.Property<int>("SoLichThucHanh")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<int>("TongGioSuDung")
                        .HasColumnType("int");

                    b.ToTable("ThongKeSuDungTheoThangViewModel");
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.ViewModels.ThongKeTheoPhongViewModel", b =>
                {
                    b.Property<decimal>("GiaTriTrungBinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaPhongMay")
                        .HasColumnType("int");

                    b.Property<string>("TenPhongMay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThietBiDangSua")
                        .HasColumnType("int");

                    b.Property<int>("ThietBiHong")
                        .HasColumnType("int");

                    b.Property<int>("ThietBiTot")
                        .HasColumnType("int");

                    b.Property<int>("TongThietBi")
                        .HasColumnType("int");

                    b.ToTable("ThongKeTheoPhongViewModel");
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.ViewModels.TrangTBViewModel", b =>
                {
                    b.Property<int?>("GiaTien")
                        .HasColumnType("int");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<int>("MaPhongMay")
                        .HasColumnType("int");

                    b.Property<int>("MaTTB")
                        .HasColumnType("int");

                    b.Property<int>("MaThuongHieu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoLanSua")
                        .HasColumnType("int");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhongMay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("TrangTBViewModel");
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.ViewModels.XuatNhapTonViewModel", b =>
                {
                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiPhieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaPhieu")
                        .HasColumnType("int");

                    b.Property<int>("MaTTB")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenNguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("XuatNhapTonViewModel");
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.Entities.DanhGiaCapDo", b =>
                {
                    b.HasOne("QLVatTuPhongThiNghiem.Models.Entities.TrangTB", "TrangTB")
                        .WithMany()
                        .HasForeignKey("MaTTB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLVatTuPhongThiNghiem.Models.Entities.NguoiDung", "NguoiDanhGia_User")
                        .WithMany()
                        .HasForeignKey("NguoiDanhGia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDanhGia_User");

                    b.Navigation("TrangTB");
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.Entities.LichSuSuaChua", b =>
                {
                    b.HasOne("QLVatTuPhongThiNghiem.Models.Entities.TrangTB", "TrangTB")
                        .WithMany()
                        .HasForeignKey("MaTTB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLVatTuPhongThiNghiem.Models.Entities.NguoiDung", "NguoiThucHien_User")
                        .WithMany()
                        .HasForeignKey("NguoiThucHien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiThucHien_User");

                    b.Navigation("TrangTB");
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.Entities.LichThucHanh", b =>
                {
                    b.HasOne("QLVatTuPhongThiNghiem.Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.Entities.TrangTB", b =>
                {
                    b.HasOne("QLVatTuPhongThiNghiem.Models.Entities.Loai", "Loai")
                        .WithMany()
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QLVatTuPhongThiNghiem.Models.Entities.PhongMay", "PhongMay")
                        .WithMany()
                        .HasForeignKey("MaPhongMay")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QLVatTuPhongThiNghiem.Models.Entities.ThuongHieu", "ThuongHieu")
                        .WithMany()
                        .HasForeignKey("MaThuongHieu")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Loai");

                    b.Navigation("PhongMay");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("QLVatTuPhongThiNghiem.Models.Entities.XuatNhapTon", b =>
                {
                    b.HasOne("QLVatTuPhongThiNghiem.Models.Entities.TrangTB", "TrangTB")
                        .WithMany()
                        .HasForeignKey("MaTTB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLVatTuPhongThiNghiem.Models.Entities.NguoiDung", "NguoiTao_User")
                        .WithMany()
                        .HasForeignKey("NguoiTao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiTao_User");

                    b.Navigation("TrangTB");
                });
#pragma warning restore 612, 618
        }
    }
}
